"""
Invoice and InvoiceLine models.

Invoice numbering format: INV-{YYYYMM}-{sequential}  (generated by agent)

GST split fields:
  - cgst_amount + sgst_amount: used for intra-state sales
  - igst_amount: used for inter-state sales
  (exactly one of the two splits is non-zero per invoice)

tally_push_status: Sprint 1 leaves all invoices at 'not_applicable'.
Full Tally integration is explicitly Phase 2+.
"""

import uuid
from decimal import Decimal
from datetime import date, datetime

from sqlalchemy import (
    TIMESTAMP,
    CheckConstraint,
    Date,
    ForeignKey,
    Index,
    Numeric,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class Invoice(Base):
    __tablename__ = "invoice"
    __table_args__ = (
        UniqueConstraint("tenant_id", "invoice_number", name="uq_invoice_number"),
        CheckConstraint(
            "status IN ('unpaid','partially_paid','paid')",
            name="ck_invoice_status",
        ),
        CheckConstraint(
            "tally_push_status IN ('not_applicable','pending','pushed')",
            name="ck_invoice_tally_status",
        ),
        Index("idx_invoice_tenant_status", "tenant_id", "status"),
        # Partial index for efficient due-date queries on unpaid invoices
        Index(
            "idx_invoice_due_date_unpaid",
            "due_date",
            postgresql_where=text("status != 'paid'"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenant.id", ondelete="CASCADE"),
        nullable=False,
    )
    customer_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("customer.id"),
        nullable=False,
    )
    # Optional link back to the quotation this was converted from
    quotation_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("quotation.id"),
        nullable=True,
    )
    invoice_number: Mapped[str] = mapped_column(Text, nullable=False)
    subtotal: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    cgst_amount: Mapped[Decimal] = mapped_column(
        Numeric(14, 2), nullable=False, default=Decimal("0")
    )
    sgst_amount: Mapped[Decimal] = mapped_column(
        Numeric(14, 2), nullable=False, default=Decimal("0")
    )
    igst_amount: Mapped[Decimal] = mapped_column(
        Numeric(14, 2), nullable=False, default=Decimal("0")
    )
    total_amount: Mapped[Decimal | None] = mapped_column(Numeric(14, 2), nullable=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, default="unpaid")
    due_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    pdf_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Sprint 1: all invoices start at 'not_applicable'. Tally sync is Phase 2+.
    tally_push_status: Mapped[str] = mapped_column(
        Text, nullable=False, default="not_applicable"
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), server_default=func.now(), nullable=False
    )


class InvoiceLine(Base):
    __tablename__ = "invoice_line"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    invoice_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("invoice.id", ondelete="CASCADE"),
        nullable=False,
    )
    item_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("item.id"),
        nullable=False,
    )
    quantity: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    # gst_rate_percent is denormalised here so the invoice is self-contained
    # even if the catalog price/rate changes later
    gst_rate_percent: Mapped[Decimal] = mapped_column(Numeric(5, 2), nullable=False)
    line_total: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)

